### PR TITLE
Do less work in sub-shells where possible

### PR DESCRIPTION
**Pull request by dushankw**
This change minimises work done in sub-shells to reduce opportunity for a non-zero exit to be masked.

The result is the script is more likely to abort (as designed) under failure cases.

### CODE REVIEW

**Comment by galaxy4public** [comment]
While I agree with the idea, I am a bit hesitant to accept the chosen approach. The `-e` with limiting execution to a single command does not make sense. Moreover, externalising sort and checksuming means that we raise our expectations on the host system where we are bootstrapping.

I will think about this and most likely will reimplemented the logic in such a way that we still do not depend on the tool availability on the host system, yet return error if anything inside the subshell goes wrong.

**Comment by dushankw** [comment]
`-e` seems like an appropriate thing to have

```
-e errexit       If not interactive, exit immediately if any untested command fails.  The exit status
                 of a command is considered to be explicitly tested if the command is used to control
                 an if, elif, while, or until; or if the command is the left hand operand of an “&&”
                 or “||” operator.
```

**Comment by galaxy4public** [comment]
It is sensible if there are two commands or more, but it is not if there is just one.

**Comment by galaxy4public** [comment]
I closely reviewed this once again and I am convinced that the proposed changes are not fixing anything.  The original problem was that "RPM" was failing to execute the given command when "/dev/urandom" was not available, but the issue was that "RPM" was not exiting with an error exit code and was returning exit code 0.  The proposed changes do not address the issue, hence closing this PR.

**Pull request closed without merging**
